-- 코드를 입력하세요
SELECT FLAVOR
FROM(
SELECT F.FLAVOR, J.TOTAL + F.TOTAL_ORDER
FROM FIRST_HALF as F JOIN 
(SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL
FROM JULY
GROUP BY FLAVOR) as J
ON F.FLAVOR = J.FLAVOR
ORDER BY 2 DESC
LIMIT 3) as R


