-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, date_format(REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE as P JOIN
REST_REVIEW as R 
ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN(
SELECT MEMBER_ID
FROM (SELECT MEMBER_ID, COUNT(*) as CNT
     FROM REST_REVIEW
     GROUP BY MEMBER_ID) as N
WHERE N.CNT = (SELECT MAX(CNT)
FROM(
SELECT MEMBER_ID, COUNT(*) as CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID) as M))
ORDER BY 3, 2