-- 코드를 입력하세요
SELECT UB.TITLE, UB.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS, DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD as UB JOIN USED_GOODS_REPLY as UR
ON UB.BOARD_ID = UR.BOARD_ID
WHERE UB.CREATED_DATE LIKE '2022-10%'
ORDER BY 6, 1