-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.SUMAM * P.PRICE as TOTAL_SALES
FROM FOOD_PRODUCT as P JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) as SUMAM, PRODUCE_DATE
FROM FOOD_ORDER 
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
GROUP BY PRODUCT_ID) as O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 3 DESC, 1 